project:
  type: website
  output-dir: _site

website:
  title: "Hands-on MinION Workshop"

  navbar:
    left:
      - href: index.qmd
        text: Protocol

      - href: github_discussions.qmd
        text: Discussion Guide

      - href: Protocol.pdf
        text: PDF Handout
        target: _blank
        
      - href: https://github.com/matthiasbirkich/minion-workshop-protocols/discussions
        text: GitHub Discussions
        target: _blank 

format:
  html:
    toc: true
    theme: cosmo
    link-external-newwindow: true
    link-external-icon: true

resources:
  - Protocol.pdf